spring:
  sdatasource:
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER}

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false

logging:
  #level:
    #ROOT: ERROR
  file:
    name: demo.log

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    logfile:
      enabled: true
      external-file: demo.log
    health:
      show-details: always
  health:
    defaults:
      enabled: true

hystrix:
  command:
    getBooksKeys:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
      metrics:
        rollingStats:
          timeoutInMilliseconds: 20000
      circuitBreaker:
        requestVolumeThreshold: 10
        errorThresholdPercentage: 50
        sleepWindowInMilliseconds: 2000
    getCommentsKeys:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000


