spring:
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
    #To check work Docker - to uncomment
    #url: ${DB_URL}
    #driver-class-name: ${DB_DRIVER}
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false

logging:
  file:
    name: demo.log

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    getBooksKeys:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
      metrics:
        rollingStats:
          timeoutInMilliseconds: 20000
      circuitBreaker:
        requestVolumeThreshold: 10
        errorThresholdPercentage: 50
        sleepWindowInMilliseconds: 2000
    getCommentsKeys:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

